version: '3.7'
services:
  vscode:
    build: .
    container_name: vscode
    user: root
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home/coder/project
      - ./.local:/home/coder/.local/share/code-server
    ports:
      - 127.0.0.1:8080:8080
